### PR TITLE
Update dependencies, rename to Matomo and some minor changes

### PR DESCRIPTION
**Pull request by Findus23**
I have no experience with Horoku and can't therefore guarantee that it still works.

### CODE REVIEW

**Comment by tsteur** [comment]
I have never used this code search, not sure if anyone does? Do we still need it? @Findus23 @mattab ?

**Comment by Findus23** [comment]
After doing this change I never again looked at it again, so I'm not so sure if we still need it.

**Comment by tsteur** [comment]
I suppose we could always reopen the PR later. @mattab should we take the tool maybe down so we don't need to maintain it also in case there's any security issue etc.?

**Comment by tsteur** [comment]
@mattab could you take the tool down? I'm not sure where it's hosted. Closing this PR for now.

**Pull request closed without merging**
